/**
 * Common constants for all features.
 */
export class CommonConstants {
  /**
   * Font weight.
   */
  static readonly FONT_WEIGHT: number = 500;

  /**
   * Scroll weight.
   */
  static readonly SCROLL_WEIGHT: number = 1;

  /**
   * Application version example.
   */
  static readonly APP_VERSION: string = '1.0.0';

  /**
   * Detail page url.
   */
  static readonly DETAIL_PAGE: string = 'pages/DetailPage';

  /**
   * Agreement page url.
   */
  static readonly AGREEMENT_PAGE: string = 'pages/AgreementPage';

  /**
   * Privacy page url.
   */
  static readonly PRIVACY_PAGE: string = 'pages/PrivacyPage';

  /**
   * About us item id.
   */
  static readonly ABOUT_US_ID: number = 1;

  /**
   * Contact item id.
   */
  static readonly CONTACT_ID: number = 2;

  /**
   * Detail page default content row.
   */
  static readonly DETAIL_DEFAULT_ROW: number = 2;

  /**
   * This is key param of data.
   */
  static readonly KEY_PARAM_DATA: string = 'data';

  /**
   * This is key param of title.
   */
  static readonly KEY_PARAM_TITLE: string = 'title';

  /**
   * Detail column title text width percentage setting.
   */
  static readonly DETAIL_COLUMN_WIDTH_PERCENT: string = '100%';

  /**
   * Detail column height percentage setting.
   */
  static readonly DETAIL_COLUMN_HEIGHT_PERCENT: string = '100%';

  /**
   * Text navigation title text width percentage setting.
   */
  static readonly NAVIGATION_TITLE_WIDTH_PERCENT: string = '100%';

  /**
   * Navigation width.
   */
  static readonly NAVIGATION_WIDTH_PERCENT: string = '100%';

  /**
   * Row width percentage setting.
   */
  static readonly ROW_WIDTH_PERCENT: string = '100%';

  /**
   * Scroll height percentage setting.
   */
  static readonly SCROLL_HEIGHT_PERCENT: string = '100%';

  /**
   * Detail column list width percentage setting.
   */
  static readonly DETAIL_LIST_WIDTH_PERCENT: string = '93.3%';

  /**
   * Divider stroke width.
   */
  static readonly DIVIDER_STROKE_WIDTH: string = '0.5vp';
}