/*
 * Copyright (c) 2022 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Common constants for all features.
 */
export class CommonConstants {

  /**
   * Minimum value of the slider for cropping the source image.
   */
  public static readonly SLICE_SLIDER_MIN: number = 0;

  /**
   * Number of decimal places reserved for slider value.
   */
  public static readonly DECIMAL_DIGITS: number = 0;

  /**
   * Adjust the step of the border image slice.
   */
  public static readonly SLIDER_STEP: number = 1;

  /**
   * Scroll layout weight.
   */
  public static readonly LAYOUT_WEIGHT: number = 1;

  /**
   * Adjust the step of the border image width.
   */
  public static readonly PREVIEW_SLIDER_STEP: number = 1;

  /**
   * Horizontal line height.
   */
  public static readonly TRANSVERSE_LINE_HEIGHT: number = 2;

  /**
   * Vertical line height.
   */
  public static readonly VERTICAL_LINE_HEIGHT: number = 2;

  /**
   * Preview slider min value, minimum border width.
   */
  public static readonly PREVIEW_SLIDER_MIN: number = 5;

  /**
   * Default value of border image slice.
   */
  public static readonly SLIDER_DEFAULT_VALUE: number = 20;

  /**
   * Default value of border image width.
   */
  public static readonly BORDER_IMAGE_SIDING = 33;

  /**
   * Maximum of border image slice.
   */
  public static readonly SLICE_SLIDER_MAX: number = 50;

  /**
   * Maximum of border image width.
   */
  public static readonly PREVIEW_SLIDER_MAX: number = 50;

  /**
   * Image max width percentage.
   */
  public static readonly IMAGE_MAX_WIDTH_PERCENTAGE: number = 100;

  /**
   * Navigation title weight.
   */
  public static readonly NAVIGATION_TITLE_WEIGHT: number = 400;

  /**
   * Palette title weight.
   */
  public static readonly TITLE_WEIGHT: number = 500;

  /**
   * Preview title weight.
   */
  public static readonly PREVIEW_TITLE_WEIGHT: number = 500;

  /**
   * Target text margin bottom.
   */
  public static readonly TARGET_TEXT_MARGIN_BOTTOM: string = '1%';

  /**
   * Text margin bottom.
   */
  public static readonly TEXT_MARGIN_BOTTOM: string = '1%';

  /**
   * Column margin left.
   */
  public static readonly COLUMN_MARGIN_LEFT: string = '3%';

  /**
   * Slider margin left.
   */
  public static readonly SLIDER_MARGIN_LEFT: string = '3.3%';

  /**
   * Stack margin left.
   */
  public static readonly STACK_MARGIN_LEFT: string = '3.3%';

  /**
   * Preview slider margin left.
   */
  public static readonly PREVIEW_SLIDER_MARGIN_LEFT: string = '3.3%';

  /**
   * Preview text hint margin left.
   */
  public static readonly PREVIEW_TEXT_HINT_MARGIN_LEFT: string = '4%';

  /**
   * Source text margin left.
   */
  public static readonly SOURCE_TEXT_MARGIN_LEFT: string = '4%';

  /**
   * Target image margin left.
   */
  public static readonly TARGET_IMAGE_MARGIN_LEFT: string = '7%';

  /**
   * Text margin left.
   */
  public static readonly TEXT_MARGIN_LEFT: string = '7%';

  /**
   * Target image margin top.
   */
  public static readonly TARGET_IMAGE_MARGIN_TOP: string = '7%';

  /**
   * Target text margin left.
   */
  public static readonly TARGET_TEXT_MARGIN_LEFT: string = '7%';

  /**
   * Text width.
   */
  public static readonly TEXT_WIDTH: string = '49%';

  /**
   * Target text width.
   */
  public static readonly TARGET_TEXT_WIDTH: string = '49%';

  /**
   * Target image width.
   */
  public static readonly TARGET_IMAGE_WIDTH: string = '86%';

  /**
   * Target image height.
   */
  public static readonly TARGET_IMAGE_HEIGHT: string = '63%';

  /**
   * Stack component width.
   */
  public static readonly STACK_WIDTH: string = '93%';

  /**
   * Stack component height.
   */
  public static readonly STACK_HEIGHT: string = '70%';

  /**
   * Border image outset.
   */
  public static readonly BORDER_IMAGE_OUTSET: string = '30px';

  /**
   * Column width.
   */
  public static readonly COLUMN_WIDTH: string = '93%';

  /**
   * Column height.
   */
  public static readonly COLUMN_HEIGHT: string = '83%';

  /**
   * Preview slider width.
   */
  public static readonly PREVIEW_SLIDER_WIDTH: string = '93%';

  /**
   * Slider width.
   */
  public static readonly SLIDER_WIDTH: string = '93%';

  /**
   * Preview column width.
   */
  public static readonly PREVIEW_COLUMN_WIDTH: string = '93%';

  /**
   * Preview column height.
   */
  public static readonly PREVIEW_COLUMN_HEIGHT: string = '83%';

  /**
   * Full width.
   */
  public static readonly FULL_WIDTH: string = '100%';

  /**
   * Full height.
   */
  public static readonly FULL_HEIGHT: string = '100%';
}