GOROOT = D:\Go
GOPATH=D:\maosiping\go;D:\Go;C:\Users\Administrator\go
build:
	D:\Go\bin\go.exe build -o websocket_server.exe C:\Users\Administrator\go\src\awesomeProject\main\main.go

run: build
	.\websocket_server.exe