/**
 * Common constants for all features.
 */
export class CommonConstants {
  /**
   * Tab size in page.
   */
  static readonly TAB_SIZE: number = 4;

  /**
   * Tab weight of page.
   */
  static readonly TABS_WEIGHT: number = 1;

  /**
   * List size of detail page.
   */
  static readonly DETAIL_LIST_SIZE: number = 2;

  /**
   * Title param in routing.
   */
  static readonly ROUTER_PARAMS_TITLE: string = 'title';

  /**
   * Url param in routing.
   */
  static readonly DETAIL_ROUTER_URL: string = 'pages/DetailPage';

  /**
   * Detail page width.
   */
  static readonly DETAIL_PAGE_WIDTH_PERCENT: string = '100%';

  /**
   * Detail page height.
   */
  static readonly DETAIL_PAGE_HEIGHT_PERCENT: string = '100%';

  /**
   * Detail page column width.
   */
  static readonly DETAIL_COLUMN_WIDTH_PERCENT: string = '93%';

  /**
   * Card content rect radius.
   */
  static readonly RECT_RADIUS: number = 24;

  /**
   * Navigation title font weight.
   */
  static readonly TITLE_FONT_WEIGHT: number = 500;

  /**
   * List title font weight.
   */
  static readonly CARD_ITEM_FONT_WEIGHT: number = 500;

  /**
   * Repeat times of list item .
   */
  static readonly REPEAT_TIMES: number = 3;

  /**
   * Page navigation width.
   */
  static readonly NAVIGATION_WIDTH_PERCENT: string = '100%';

  /**
   * Widget height of list item.
   */
  static readonly WIDGET_HEIGHT_PERCENT: string = '100%';

  /**
   * Card content scroll width.
   */
  static readonly SCROLL_WIDTH_PERCENT: string = '100%';

  /**
   * Card content scroll height.
   */
  static readonly SCROLL_HEIGHT_PERCENT: string = '100%';

  /**
   * Card content rect width.
   */
  static readonly RECT_WIDTH_PERCENT: string = '100%';

  /**
   * List item row width.
   */
  static readonly ROW_WIDTH_PERCENT: string = '100%';

  /**
   * Tab bar width.
   */
  static readonly TAB_BAR_WIDTH_PERCENT: string = '100%';
}