/**
 * Common constants for all features.
 */
export class CommonConstants {
  /**
   * Top grid count.
   */
  static readonly TOP_GRID_COUNT: number = 8;

  /**
   * Bottom grid count.
   */
  static readonly BOTTOM_GRID_COUNT: number = 32;

  /**
   * Font weight of text in Grid.
   */
  static readonly GRID_ITEM_FONT_WEIGHT: number = 400;

  /**
   * Font weight of text.
   */
  static readonly TEXT_FONT_WEIGHT: number = 500;

  /**
   * Font weight of navigation title.
   */
  static readonly TITLE_FONT_WEIGHT: number = 500;

  /**
   * Layout weight of scroll.
   */
  static readonly SCROLL_LAYOUT_WEIGHT: number = 1;

  /**
   * Grid columns template.
   */
  static readonly COLUMNS_TEMPLATE: string = '1fr 1fr 1fr 1fr';

  /**
   * Percent of the navigation width.
   */
  static readonly NAVIGATION_WIDTH_PERCENT: string = '100%';

  /**
   * Percent of the grid page height.
   */
  static readonly GRID_PAGE_HEIGHT_PERCENT: string = '100%';

  /**
   * Percent of the text width.
   */
  static readonly TEXT_WIDTH_PERCENT: string = '100%';
}