/*
 * Copyright (c) 2022 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Common constants for all feature.
 */
export default class CommonConstants{
  /**
   * Text font weight.
   */
  static readonly TEXT_FONT_WEIGHT: number = 500;

  /**
   * Layout weight of the scroll.
   */
  static readonly SCROLL_LAYOUT_WEIGHT: number = 1;

  /**
   * Width of the button.
   */
  static readonly BUTTON_WIDTH: string = '86.7%';

  /**
   * Column template of the grid.
   */
  static readonly COLUMN_TEMPLATE: string = '1fr 1fr 1fr 1fr 1fr';

  /**
   * Row template of the grid.
   */
  static readonly ROW_TEMPLATE: string = '1fr 1fr 1fr 1fr';

  /**
   * Full heigth percent.
   */
  static readonly FULL_HEIGHT: string = '100%';

  /**
   * Full width percent.
   */
  static readonly FULL_WIDTH: string = '100%';
}